# g++, clang++, icpc are supported.
CXX ?= g++
CXXFLAGS = -std=c++17 -lr

all: 1 2 3 4

1:
	${CXX} 1.cc -o 1 ${CXXFLAGS}
               
               
2:             
	${CXX} 2.cc -o 2 ${CXXFLAGS}
               
               
3:             
	${CXX} 3.cc -o 3 ${CXXFLAGS}
               
               
4:             
	${CXX} 4.cc -o 4 ${CXXFLAGS}




