CXX ?= g++
all: 1 2 3 4

1:
	${CXX} -std=c++17 -static -static-libstdc++ 1.cc -o 1.exe

2:
	${CXX} -std=c++17 -static -static-libstdc++ 2.cc -o 2.exe

3:
	${CXX} -std=c++17 -static -static-libstdc++ 3.cc -o 3.exe

4:
	${CXX} -std=c++17 -static -static-libstdc++ 4.cc -o 4.exe

clean:
	rm -f *.exe
