language: cpp
script: cd src && cmake -DCMAKE_BUILD_TYPE=Release . && make

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7
            - libboost1.54-all-dev
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
    - eval "${MATRIX_EVAL}"
    - mkdir $HOME/usr
    - export PATH="$HOME/usr/bin:$PATH"
    - wget https://cmake.org/files/v3.9/cmake-3.9.1-Linux-x86_64.sh
    - chmod +x cmake-3.9.1-Linux-x86_64.sh
    - ./cmake-3.9.1-Linux-x86_64.sh --prefix=$HOME/usr --exclude-subdir --skip-license

addons:
  apt:
    sources:
      - george-edison55-precise-backports
