
1:
	masm 1.asm
	tlink 1.obj,1.exe,,

2:
	masm kbint.asm
	tlink /3 kbint.obj,2i.exe,,
	masm kbun.asm
	tlink /3 kbun.obj,2u.exe,,

3:
	masm cmos.asm
	tlink /3 cmos.obj,3.exe,,

test:
	masm test.asm
	tlink /3 test.obj,test.exe,,

origin:
	masm origin.asm
	tlink /3 origin.obj,origin.exe,,

